name: warehouse
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  image_picker: ^0.8.4+11
  injectable: ^2.1.0
  internet_connection_checker: any
  json_annotation: ^4.8.1
  form_builder_validators: ^9.0.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.4

  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.5

  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
